server:
  port: 8080

spring:
  application:
    name: api-gateway

product:
  service:
    url: http://localhost:8082

order:
  service:
    url: http://localhost:8083

inventory:
  service:
    url: http://localhost:8084

user:
  service:
    url: http://localhost:8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: inventory-service
        url: /inventory-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
