server:
  port: 8084
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: Sadaf#007
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  server:
    forward-headers-strategy: framework
  swagger-ui:
    path: /swagger-ui.html
